import {Component} from '@angular/core';
import {NavController, NavParams} from 'ionic-angular';
import {ItemDetailsPage} from '../item-details/item-details';


@Component({
  templateUrl: 'build/pages/list/list.html'
})
export class ListPage {
  selectedItem: any;
  icons: string[];
  pokemons: Object[];

  constructor(private nav: NavController, navParams: NavParams) {
    // If we navigated to this page, we will have an item available as a nav param
    this.selectedItem = navParams.get('pokemon');

    this.pokemons = [
      {name: 'Bulbasaur', types: ['Grass', 'Poison'], evolCandy: 25, eggKm: 2,  fastAttacks: ['Tackle', 'Vine Whip'], specialAttacks: ['Sludge Bomb', 'Seed Bomb', 'Power Whip']},
      {name: 'Ivysaur', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Venusaur', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Charmander', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Charmeleon', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Charizard', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Squirtle', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Wartortle', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Blastoise', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Caterpie', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Metapod', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Butterfree', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Weedle', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Kakuna', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Beedrill', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Pidgey', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Pidgeotto', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Pidgeot', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Rattata', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Raticate', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Spearow', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Fearow', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Ekans', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Pikachu', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Raichu', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Sandshrew', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Sandslash', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Nidoran♀', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Nidorina', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Nidoqueen', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Nidoran♂', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Nidorino', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Nidoking', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Clefairy', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Clefable', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Vulpix', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Ninetales', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Jigglypuff', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Wigglytuff', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Zubat', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Golbat', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Oddish', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Gloom', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Vileplume', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Paras', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Parasect', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Venonat', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Venomoth', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Diglett', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Dugtrio', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Meowth', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Persian', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Psyduck', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Golduck', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Mankey', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Primeape', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Growlithe', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Arcanine', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Poliwag', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Poliwhirl', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Poliwrath', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Abra', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Kadabra', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Alakazam', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Machop', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Machoke', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Machamp', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Bellsprout', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Weepinbell', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Victreebel', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Tentacool', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Tentacruel', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Geodude', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Graveler', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Golem', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Ponyta', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Rapidash', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Slowpoke', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Slowbro', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Magnemite', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Magneton', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Farfetch\'d', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Doduo', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Dodrio', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Seel', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Dewgong', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Grimer', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Muk', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Shellder', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Cloyster', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Gastly', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Haunter', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Gengar', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Onix', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Drowzee', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Hypno', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Krabby', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Kingler', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Voltorb', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Electrode', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Exeggcute', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Exeggutor', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Cubone', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Marowak', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Hitmonlee', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Hitmonchan', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Lickitung', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Koffing', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Weezing', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Rhyhorn', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Rhydon', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Chansey', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Tangela', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Kangaskhan', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Horsea', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Seadra', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Goldeen', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Seaking', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Staryu', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Starmie', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Mr. Mime', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Scyther', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Jynx', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Electabuzz', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Magmar', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Pinsir', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Tauros', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Magikarp', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Gyarados', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Lapras', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Ditto', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Eevee', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Vaporeon', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Jolteon', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Flareon', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Porygon', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Omanyte', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Omastar', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Kabuto', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Kabutops', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Aerodactyl', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Snorlax', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Articuno', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Zapdos', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Moltres', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Dratini', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Dragonair', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Dragonite', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Mewtwo', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']},
      {name: 'Mew', types: [''], evolCandy: 0, eggKm: 2, fastAttacks: [''], specialAttacks: ['']}
    ];

  }

  itemTapped(event, pokemon) {
    this.nav.push(ItemDetailsPage, {
      pokemon: pokemon
    });
  }
}
