import {Component} from '@angular/core';
import {NavController, NavParams} from 'ionic-angular';
import {ItemDetailsPage} from '../item-details/item-details';


@Component({
  templateUrl: 'build/pages/list/list.html'
})
export class ListPage {
  selectedItem: any;
  icons: string[];
  pokemons: Object[];

  constructor(private nav: NavController, navParams: NavParams) {
    // If we navigated to this page, we will have an item available as a nav param
    this.selectedItem = navParams.get('pokemon');

    this.pokemons = [
        {name: 'Abra', types: ['Psychic'], evolCandy: '25 Abra', eggKm: 5, evolFrom: null, evolTo: ['Kadabra'], rarity: 2.44},
        {name: 'Aerodactyl', types: ['Rock', 'Flying'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.09},
        {name: 'Alakazam', types: ['Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Kadabra'], evolTo: null, rarity: 0.05},
        {name: 'Arbok', types: ['Poison'], evolCandy: null, eggKm: null, evolFrom: ['Ekans'], evolTo: null, rarity: 0.22},
        {name: 'Arcanine', types: ['Fire'], evolCandy: null, eggKm: null, evolFrom: ['Growlithe'], evolTo: null, rarity: 0.16},
        {name: 'Articuno', types: ['Ice', 'Flying'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null, rarity: null},
        {name: 'Beedrill', types: ['Bug', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Kakuna'], evolTo: null, rarity: 0.21},
        {name: 'Bellsprout', types: ['Grass', 'Poison'], evolCandy: '25 Bellsprout', eggKm: 5, evolFrom: null, evolTo: ['Weepinbell'], rarity: 1.11},
        {name: 'Blastoise', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Wartortle'], evolTo: null, rarity: 0.02},
        {name: 'Bulbasaur', types: ['Grass', 'Poison'], evolCandy: '25 Bulbasaur', eggKm: 2, evolFrom: null, evolTo: ['Ivysaur'], rarity: 1.00},
        {name: 'Butterfree', types: ['Bug', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Metapod'], evolTo: null, rarity: 0.09},
        {name: 'Caterpie', types: ['Bug'], evolCandy: '12 Caterpie', eggKm: 2, evolFrom: null, evolTo: ['Metapod'], rarity: 2.23},
        {name: 'Chansey', types: ['Normal'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.19},
        {name: 'Charizard', types: ['Fire', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Charmeleon'], evolTo: null, rarity: 0.01},
        {name: 'Charmander', types: ['Fire'], evolCandy: '25 Charmander', eggKm: 2, evolFrom: null, evolTo: ['Charmeleon'], rarity: 0.53},
        {name: 'Charmeleon', types: ['Fire'], evolCandy: '100 Charmander', eggKm: null, evolFrom: ['Charmander'], evolTo: ['Charizard'], rarity: 0.06},
        {name: 'Clefable', types: ['Fairy'], evolCandy: null, eggKm: null, evolFrom: ['Clefairy'], evolTo: null, rarity: 0.04},
        {name: 'Clefairy', types: ['Fairy'], evolCandy: '50 Clefairy', eggKm: 2, evolFrom: null, evolTo: ['Clefable'], rarity: 0.84},
        {name: 'Cloyster', types: ['Water', 'Ice'], evolCandy: null, eggKm: null, evolFrom: ['Shellder'], evolTo: null, rarity: 0.06},
        {name: 'Cubone', types: ['Ground'], evolCandy: '50 Cubone', eggKm: 5, evolFrom: null, evolTo: ['Marowak'], rarity: 0.58},
        {name: 'Dewgong', types: ['Water', 'Ice'], evolCandy: null, eggKm: null, evolFrom: ['Seel'], evolTo: null, rarity: 0.015},
        {name: 'Diglett', types: ['Ground'], evolCandy: '50 Diglett', eggKm: 5, evolFrom: null, evolTo: ['Dugtrio'], rarity: 0.74},
        {name: 'Ditto', types: ['Normal'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null, rarity: null},
        {name: 'Dodrio', types: ['Normal', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Doduo'], evolTo: null, rarity: 0.10},
        {name: 'Doduo', types: ['Normal', 'Flying'], evolCandy: '50 Doduo', eggKm: 5, evolFrom: null, evolTo: ['Dodrio'], rarity: 0.89},
        {name: 'Dragonair', types: ['Dragon'], evolCandy: '100 Dratini', eggKm: null, evolFrom: ['Dratini'], evolTo: ['Dragonite'], rarity: 0.04},
        {name: 'Dragonite', types: ['Dragon', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Dragonair'], evolTo: null, rarity: 0.02},
        {name: 'Dratini', types: ['Dragon'], evolCandy: '25 Dratini', eggKm: 10, evolFrom: null, evolTo: ['Dragonair'], rarity: 0.35},
        {name: 'Drowzee', types: ['Psychic'], evolCandy: '50 Drowzee', eggKm: 5, evolFrom: null, evolTo: ['Hypno'], rarity: 1.97},
        {name: 'Dugtrio', types: ['Ground'], evolCandy: null, eggKm: null, evolFrom: ['Diglett'], evolTo: null, rarity: 0.09},
        {name: 'Eevee', types: ['Normal'], evolCandy: '25 Eevee', eggKm: 10, evolFrom: null, evolTo: ['Vaporeon', 'Jolteon', 'Flareon'], rarity: 3.22},
        {name: 'Ekans', types: ['Poison'], evolCandy: '50 Ekans', eggKm: 5, evolFrom: null, evolTo: ['Arbok'], rarity: 2.21},
        {name: 'Electabuzz', types: ['Electric'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.29},
        {name: 'Electrode', types: ['Electric'], evolCandy: null, eggKm: null, evolFrom: ['Voltorb'], evolTo: null, rarity: 0.18},
        {name: 'Exeggcute', types: ['Grass', 'Psychic'], evolCandy: '50 Exeggcute', eggKm: 5, evolFrom: null, evolTo: ['Exeggutor'], rarity: 0.68},
        {name: 'Exeggutor', types: ['Grass', 'Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Exeggcute'], evolTo: null, rarity: 0.05},
        {name: 'Farfetch\'d', types: ['Normal', 'Flying'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null, rarity: null},
        {name: 'Fearow', types: ['Normal', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Spearow'], evolTo: null, rarity: 0.37},
        {name: 'Flareon', types: ['Fire'], evolCandy: null, eggKm: null, evolFrom: ['Eevee'], evolTo: null, rarity: 0.14},
        {name: 'Gastly', types: ['Ghost', 'Poison'], evolCandy: '25 Gastly', eggKm: 5, evolFrom: null, evolTo: ['Haunter'], rarity: 2.17},
        {name: 'Gengar', types: ['Ghost', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Haunter'], evolTo: null, rarity: 0.04},
        {name: 'Geodude', types: ['Rock', 'Ground'], evolCandy: '25 Geodude', eggKm: 2, evolFrom: null, evolTo: ['Graveler'], rarity: 1.96},
        {name: 'Gloom', types: ['Grass', 'Poison'], evolCandy: '100 Oddish', eggKm: null, evolFrom: ['Oddish'], evolTo: ['Vileplume'], rarity: 0.13},
        {name: 'Golbat', types: ['Poison', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Zubat'], evolTo: null, rarity: 0.40},
        {name: 'Goldeen', types: ['Water'], evolCandy: '50 Goldeen', eggKm: 5, evolFrom: null, evolTo: ['Seaking'], rarity: 0.60},
        {name: 'Golduck', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Psyduck'], evolTo: null, rarity: 0.07},
        {name: 'Golem', types: ['Rock', 'Ground'], evolCandy: null, eggKm: null, evolFrom: ['Graveler'], evolTo: null, rarity: 0.05},
        {name: 'Graveler', types: ['Rock', 'Ground'], evolCandy: '100 Geodude', eggKm: null, evolFrom: ['Geodude'], evolTo: ['Golem'], rarity: 0.30},
        {name: 'Grimer', types: ['Poison'], evolCandy: '50 Grimer', eggKm: 5, evolFrom: null, evolTo: ['Muk'], rarity: 0.12},
        {name: 'Growlithe', types: ['Fire'], evolCandy: '50 Growlithe', eggKm: 5, evolFrom: null, evolTo: ['Arcanine'], rarity: 1.66},
        {name: 'Gyarados', types: ['Water', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Magikarp'], evolTo: ['Gyarados'], rarity: 0.02},
        {name: 'Haunter', types: ['Ghost', 'Poison'], evolCandy: '100 Gastly', eggKm: null, evolFrom: ['Gastly'], evolTo: ['Gengar'], rarity: 0.24},
        {name: 'Hitmonchan', types: ['Fight'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.30},
        {name: 'Hitmonlee', types: ['Fight'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.37},
        {name: 'Horsea', types: ['Water'], evolCandy: '50 Horsea', eggKm: 5, evolFrom: null, evolTo: ['Seadra'], rarity: 0.53},
        {name: 'Hypno', types: ['Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Drowzee'], evolTo: null, rarity: 0.21},
        {name: 'Ivysaur', types: ['Grass', 'Poison'], evolCandy: '100 Bulbasaur', eggKm: null, evolFrom: ['Bulbasaur'], evolTo: ['Venusaur'], rarity: 0.11},
        {name: 'Jigglypuff', types: ['Normal', 'Fairy'], evolCandy: '50 Jigglypuff', eggKm: 2, evolFrom: null, evolTo: ['Wigglytuff'], rarity: 0.97},
        {name: 'Jolteon', types: ['Electric'], evolCandy: null, eggKm: null, evolFrom: ['Eevee'], evolTo: null, rarity: 0.09},
        {name: 'Jynx', types: ['Ice', 'Psychic'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.51},
        {name: 'Kabuto', types: ['Rock', 'Water'], evolCandy: '50 Kabuto', eggKm: 10, evolFrom: null, evolTo: ['Kabutops'], rarity: 0.14},
        {name: 'Kabutops', types: ['Rock', 'Water'], evolCandy: null, eggKm: null, evolFrom: ['Kabuto'], evolTo: null, rarity: 0.02},
        {name: 'Kadabra', types: ['Psychic'], evolCandy: '100 Abra', eggKm: null, evolFrom: ['Abra'], evolTo: ['Alakazam'], rarity: 0.24},
        {name: 'Kakuna', types: ['Bug', 'Poison'], evolCandy: '50 Weedle', eggKm: null, evolFrom: ['Weedle'], evolTo: ['Beedrill'], rarity: 0.52},
        {name: 'Kangaskhan', types: ['Normal'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null, rarity: 0.012},
        {name: 'Kingler', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Krabby'], evolTo: null, rarity: 0.13},
        {name: 'Koffing', types: ['Poison'], evolCandy: '50 Koffing', eggKm: 5, evolFrom: null, evolTo: ['Weezing'], rarity: 0.26},
        {name: 'Krabby', types: ['Water'], evolCandy: '50 Krabby', eggKm: 5, evolFrom: null, evolTo: ['Kingler'], rarity: 0.95},
        {name: 'Lapras', types: ['Water', 'Ice'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.02},
        {name: 'Lickitung', types: ['Normal'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null, rarity: 0.14},
        {name: 'Machamp', types: ['Fight'], evolCandy: null, eggKm: null, evolFrom: ['Machoke'], evolTo: null, rarity: 0.03},
        {name: 'Machoke', types: ['Fight'], evolCandy: '100 Machop', eggKm: null, evolFrom: ['Machop'], evolTo: ['Machamp'], rarity: 0.09},
        {name: 'Machop', types: ['Fight'], evolCandy: '25 Machop', eggKm: 5, evolFrom: null, evolTo: ['Machoke'], rarity: 0.92},
        {name: 'Magikarp', types: ['Water'], evolCandy: '400 Magikarp', eggKm: 2, evolFrom: null, evolTo: ['Gyarados'], rarity: 0.82},
        {name: 'Magmar', types: ['Fire'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.26},
        {name: 'Magnemite', types: ['Electric', 'Steel'], evolCandy: '50 Magnemite', eggKm: 5, evolFrom: null, evolTo: ['Magneton'], rarity: 1.98},
        {name: 'Magneton', types: ['Electric', 'Steel'], evolCandy: null, eggKm: null, evolFrom: ['Magnemite'], evolTo: null, rarity: 0.20},
        {name: 'Mankey', types: ['Fight'], evolCandy: '50 Mankey', eggKm: 5, evolFrom: null, evolTo: ['Primeape'], rarity: 0.93},
        {name: 'Marowak', types: ['Ground'], evolCandy: null, eggKm: null, evolFrom: ['Cubone'], evolTo: null, rarity: 0.05},
        {name: 'Meowth', types: ['Normal'], evolCandy: '50 Meowth', eggKm: 5, evolFrom: null, evolTo: ['Persian'], rarity: 3.14},
        {name: 'Metapod', types: ['Bug'], evolCandy: '50 Caterpie', eggKm: null, evolFrom: ['Caterpie'], evolTo: ['Butterfree'], rarity: 0.32},
        {name: 'Mew', types: ['Psychic'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null, rarity: null},
        {name: 'Mewtwo', types: ['Psychic'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null, rarity: null},
        {name: 'Moltres', types: ['Fire', 'Flying'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null, rarity: null},
        {name: 'Mr. Mime', types: ['Psychic', 'Fairy'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.02},
        {name: 'Muk', types: ['Poison'], evolCandy: null, eggKm: null, evolFrom: ['Grimer'], evolTo: null, rarity: 0.014},
        {name: 'Nidoking', types: ['Poison', 'Ground'], evolCandy: null, eggKm: null, evolFrom: ['Nidorino'], evolTo: null, rarity: 0.07},
        {name: 'Nidoqueen', types: ['Poison', 'Ground'], evolCandy: null, eggKm: null, evolFrom: ['Nidorina'], evolTo: null, rarity: 0.06},
        {name: 'Nidoran♀', types: ['Poison'], evolCandy: '25 Nidoran♀', eggKm: 5, evolFrom: [''], evolTo: ['Nidorina'], rarity: 1.81},
        {name: 'Nidoran♂', types: ['Poison'], evolCandy: '25 Nidoran♂', eggKm: 5, evolFrom: null, evolTo: ['Nidorino'], rarity: 1.62},
        {name: 'Nidorina', types: ['Poison'], evolCandy: '100 Nidoran♀', eggKm: null, evolFrom: ['Nidoran♀'], evolTo: ['Nidoqueen'], rarity: 0.21},
        {name: 'Nidorino', types: ['Poison'], evolCandy: '100 Nidoran♂', eggKm: null, evolFrom: ['Nidoran♂'], evolTo: ['Nidoking'], rarity: 0.15},
        {name: 'Ninetales', types: ['Fire'], evolCandy: null, eggKm: null, evolFrom: ['Vulpix'], evolTo: null, rarity: 0.15},
        {name: 'Oddish', types: ['Grass', 'Poison'], evolCandy: '25 Oddish', eggKm: 5, evolFrom: null, evolTo: ['Gloom'], rarity: 1.27},
        {name: 'Omanyte', types: ['Rock', 'Water'], evolCandy: '50 Omanyte', eggKm: 10, evolFrom: null, evolTo: ['Omastar'], rarity: 0.15},
        {name: 'Omastar', types: ['Rock', 'Water'], evolCandy: null, eggKm: null, evolFrom: ['Omanyte'], evolTo: null, rarity: 0.016},
        {name: 'Onix', types: ['Rock', 'Ground'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.25},
        {name: 'Paras', types: ['Bug', 'Grass'], evolCandy: '50 Paras', eggKm: 5, evolFrom: null, evolTo: ['Parasect'], rarity: 2.18},
        {name: 'Parasect', types: ['Bug', 'Grass'], evolCandy: null, eggKm: null, evolFrom: ['Paras'], evolTo: null, rarity: 0.21},
        {name: 'Persian', types: ['Normal'], evolCandy: null, eggKm: null, evolFrom: ['Meowth'], evolTo: null, rarity: 0.25},
        {name: 'Pidgeot', types: ['Normal', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Pidgeotto'], evolTo: null, rarity: 0.37},
        {name: 'Pidgeotto', types: ['Normal', 'Flying'], evolCandy: '50 Pidgey', eggKm: null, evolFrom: ['Pidgey'], evolTo: ['Pidgeot'], rarity: 1.34},
        {name: 'Pidgey', types: ['Normal', 'Flying'], evolCandy: '12 Pidgey', eggKm: 2, evolFrom: null, evolTo: ['Pidgeotto'], rarity: 8.54},
        {name: 'Pikachu', types: ['Electric'], evolCandy: '50 Pikachu', eggKm: 2, evolFrom: null, evolTo: ['Raichu'], rarity: 0.96},
        {name: 'Pinsir', types: ['Bug'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.78},
        {name: 'Poliwag', types: ['Water'], evolCandy: '25 Poliwag', eggKm: 5, evolFrom: null, evolTo: ['Poliwhirl'], rarity: 0.70},
        {name: 'Poliwhirl', types: ['Water'], evolCandy: '100 Poliwag', eggKm: null, evolFrom: ['Poliwag'], evolTo: ['Poliwrath'], rarity: 0.13},
        {name: 'Poliwrath', types: ['Water', 'Fight'], evolCandy: null, eggKm: null, evolFrom: ['Poliwhirl'], evolTo: null, rarity: 0.013},
        {name: 'Ponyta', types: ['Fire'], evolCandy: '50 Ponyta', eggKm: 5, evolFrom: null, evolTo: ['Rapidash'], rarity: 1.32},
        {name: 'Porygon', types: ['Normal'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null, rarity: 0.42},
        {name: 'Primeape', types: ['Fight'], evolCandy: null, eggKm: null, evolFrom: ['Mankey'], evolTo: null, rarity: 0.13},
        {name: 'Psyduck', types: ['Water'], evolCandy: '50 Psyduck', eggKm: 5, evolFrom: null, evolTo: ['Golduck'], rarity: 0.64},
        {name: 'Raichu', types: ['Electric'], evolCandy: null, eggKm: null, evolFrom: ['Pikachu'], evolTo: null, rarity: 0.04},
        {name: 'Rapidash', types: ['Fire'], evolCandy: null, eggKm: null, evolFrom: ['Ponyta'], evolTo: null, rarity: 0.16},
        {name: 'Raticate', types: ['Normal'], evolCandy: null, eggKm: null, evolFrom: ['Rattata'], evolTo: null, rarity: 0.99},
        {name: 'Rattata', types: ['Normal'], evolCandy: '25 Rattata', eggKm: 2, evolFrom: null, evolTo: ['Raticate'], rarity: 9.70},
        {name: 'Rhydon', types: ['Ground', 'Rock'], evolCandy: null, eggKm: null, evolFrom: ['Rhyhorn'], evolTo: null, rarity: 0.12},
        {name: 'Rhyhorn', types: ['Ground', 'Rock'], evolCandy: '50 Rhyhorn', eggKm: 5, evolFrom: null, evolTo: ['Rhydon'], rarity: 0.81},
        {name: 'Sandshrew', types: ['Ground'], evolCandy: '50 Sandshrew', eggKm: 5, evolFrom: null, evolTo: ['Sandslash'], rarity: 0.66},
        {name: 'Sandslash', types: ['Ground'], evolCandy: null, eggKm: null, evolFrom: ['Sandshrew'], evolTo: null, rarity: 0.07},
        {name: 'Scyther', types: ['Bug', 'Flying'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.38},
        {name: 'Seadra', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Horsea'], evolTo: null, rarity: 0.07},
        {name: 'Seaking', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Goldeen'], evolTo: [null], rarity: 0.09},
        {name: 'Seel', types: ['Water'], evolCandy: '50 Seel', eggKm: 5, evolFrom: null, evolTo: ['Dewgong'], rarity: 0.23},
        {name: 'Shellder', types: ['Water'], evolCandy: '50 Shellder', eggKm: 5, evolFrom: null, evolTo: ['Cloyster'], rarity: 0.33},
        {name: 'Slowbro', types: ['Water', 'Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Slowpoke'], evolTo: null, rarity: 0.07},
        {name: 'Slowpoke', types: ['Water', 'Psychic'], evolCandy: '50 Slowpoke', eggKm: 5, evolFrom: null, evolTo: ['Slowbro'], rarity: 0.47},
        {name: 'Snorlax', types: ['Normal'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null, rarity: 0.26},
        {name: 'Spearow', types: ['Normal', 'Flying'], evolCandy: '50 Spearow', eggKm: 2, evolFrom: null, evolTo: ['Fearow'], rarity: 2.18},
        {name: 'Squirtle', types: ['Water'], evolCandy: '25 Squirtle', eggKm: 2, evolFrom: null, evolTo: ['Wartortle'], rarity: 0.77},
        {name: 'Starmie', types: ['Water', 'Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Staryu'], evolTo: null, rarity: 0.09},
        {name: 'Staryu', types: ['Water'], evolCandy: '50 Staryu', eggKm: 5, evolFrom: null, evolTo: ['Starmie'], rarity: 0.75},
        {name: 'Tangela', types: ['Grass'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null, rarity: 0.30},
        {name: 'Tauros', types: ['Normal'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null, rarity: 0.56},
        {name: 'Tentacool', types: ['Water', 'Poison'], evolCandy: '50 Tentacool', eggKm: 5, evolFrom: null, evolTo: ['Tentacruel'], rarity: 0.19},
        {name: 'Tentacruel', types: ['Water', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Tentacool'], evolTo: null, rarity: 0.11},
        {name: 'Vaporeon', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Eevee'], evolTo: null, rarity: 0.05},
        {name: 'Venomoth', types: ['Bug', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Venonat'], evolTo: null, rarity: 0.23},
        {name: 'Venonat', types: ['Bug', 'Poison'], evolCandy: '50 Venonat', eggKm: 5, evolFrom: null, evolTo: ['Venomoth'], rarity: 2.17},
        {name: 'Venusaur', types: ['Grass', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Ivysaur'], evolTo: null, rarity: 0.02},
        {name: 'Victreebel', types: ['Grass', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Weepinbell'], evolTo: null, rarity: 0.03},
        {name: 'Vileplume', types: ['Grass', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Gloom'], evolTo: null, rarity: 0.03},
        {name: 'Voltorb', types: ['Electric'], evolCandy: '50 Voltorb', eggKm: 5, evolFrom: null, evolTo: ['Electrode'], rarity: 1.84},
        {name: 'Vulpix', types: ['Fire'], evolCandy: '50 Vulpix', eggKm: 5, evolFrom: null, evolTo: ['Ninetales'], rarity: 1.21},
        {name: 'Wartortle', types: ['Water'], evolCandy: '100 Squirtle', eggKm: null, evolFrom: ['Squirtle'], evolTo: ['Blastoise'], rarity: 0.07},
        {name: 'Weedle', types: ['Bug', 'Poison'], evolCandy: '12 Weedle', eggKm: 2, evolFrom: null, evolTo: ['Kakuna'], rarity: 4.03},
        {name: 'Weepinbell', types: ['Grass', 'Poison'], evolCandy: '100 Bellsprout', eggKm: null, evolFrom: ['Bellsprout'], evolTo: ['Victreebel'], rarity: 0.15},
        {name: 'Weezing', types: ['Poison'], evolCandy: null, eggKm: null, evolFrom: ['Koffing'], evolTo: null, rarity: 0.02},
        {name: 'Wigglytuff', types: ['Normal', 'Fairy'], evolCandy: null, eggKm: null, evolFrom: ['Jigglypuff'], evolTo: null, rarity: 0.07},
        {name: 'Zapdos', types: ['Electric', 'Flying'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null, rarity: null},
        {name: 'Zubat', types: ['Poison', 'Flying'], evolCandy: '50 Zubat', eggKm: 2, evolFrom: null, evolTo: ['Golbat'], rarity: 3.42}
    ];

  }

  itemTapped(event, pokemon) {
    this.nav.push(ItemDetailsPage, {
      pokemon: pokemon
    });
  }
}
