import {Component} from '@angular/core';
import {NavController, NavParams} from 'ionic-angular';
import {ItemDetailsPage} from '../item-details/item-details';


@Component({
  templateUrl: 'build/pages/list/list.html'
})
export class ListPage {
  selectedItem: any;
  icons: string[];
  pokemons: Object[];

  constructor(private nav: NavController, navParams: NavParams) {
    // If we navigated to this page, we will have an item available as a nav param
    this.selectedItem = navParams.get('pokemon');

    this.pokemons = [
        {name: 'Abra', types: ['Psychic'], evolCandy: '25 Abra', eggKm: 5, evolFrom: null, evolTo: ['Kadabra']},
        {name: 'Aerodactyl', types: ['Rock', 'Flying'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Alakazam', types: ['Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Kadabra'], evolTo: null},
        {name: 'Arbok', types: ['Poison'], evolCandy: null, eggKm: null, evolFrom: ['Ekans'], evolTo: null},
        {name: 'Arcanine', types: ['Fire'], evolCandy: null, eggKm: null, evolFrom: ['Growlithe'], evolTo: null},
        {name: 'Articuno', types: ['Ice', 'Flying'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null},
        {name: 'Beedrill', types: ['Bug', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Kakuna'], evolTo: null},
        {name: 'Bellsprout', types: ['Grass', 'Poison'], evolCandy: '25 Bellsprout', eggKm: 5, evolFrom: null, evolTo: ['Weepinbell']},
        {name: 'Blastoise', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Wartortle'], evolTo: null},
        {name: 'Bulbasaur', types: ['Grass', 'Poison'], evolCandy: '25 Bulbasaur', eggKm: 2, evolFrom: null, evolTo: ['Ivysaur']},
        {name: 'Butterfree', types: ['Bug', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Metapod'], evolTo: null},
        {name: 'Caterpie', types: ['Bug'], evolCandy: '12 Caterpie', eggKm: 2, evolFrom: null, evolTo: ['Metapod']},
        {name: 'Chansey', types: ['Normal'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Charizard', types: ['Fire', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Charmeleon'], evolTo: null},
        {name: 'Charmander', types: ['Fire'], evolCandy: '25 Charmander', eggKm: 2, evolFrom: null, evolTo: ['Charmeleon']},
        {name: 'Charmeleon', types: ['Fire'], evolCandy: '100 Charmander', eggKm: null, evolFrom: ['Charmander'], evolTo: ['Charizard']},
        {name: 'Clefable', types: ['Fairy'], evolCandy: null, eggKm: null, evolFrom: ['Clefairy'], evolTo: null},
        {name: 'Clefairy', types: ['Fairy'], evolCandy: '50 Clefairy', eggKm: 2, evolFrom: null, evolTo: ['Clefable']},
        {name: 'Cloyster', types: ['Water', 'Ice'], evolCandy: null, eggKm: null, evolFrom: ['Shellder'], evolTo: null},
        {name: 'Cubone', types: ['Ground'], evolCandy: '50 Cubone', eggKm: 5, evolFrom: null, evolTo: ['Marowak']},
        {name: 'Dewgong', types: ['Water', 'Ice'], evolCandy: null, eggKm: null, evolFrom: ['Seel'], evolTo: null},
        {name: 'Diglett', types: ['Ground'], evolCandy: '50 Diglett', eggKm: 5, evolFrom: null, evolTo: ['Dugtrio']},
        {name: 'Ditto', types: ['Normal'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null},
        {name: 'Dodrio', types: ['Normal', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Doduo'], evolTo: null},
        {name: 'Doduo', types: ['Normal', 'Flying'], evolCandy: '50 Doduo', eggKm: 5, evolFrom: null, evolTo: ['Dodrio']},
        {name: 'Dragonair', types: ['Dragon'], evolCandy: '100 Dratini', eggKm: null, evolFrom: ['Dratini'], evolTo: ['Dragonite']},
        {name: 'Dragonite', types: ['Dragon', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Dragonair'], evolTo: null},
        {name: 'Dratini', types: ['Dragon'], evolCandy: '25 Dratini', eggKm: 10, evolFrom: null, evolTo: ['Dragonair']},
        {name: 'Drowzee', types: ['Psychic'], evolCandy: '50 Drowzee', eggKm: 5, evolFrom: null, evolTo: ['Hypno']},
        {name: 'Dugtrio', types: ['Ground'], evolCandy: null, eggKm: null, evolFrom: ['Diglett'], evolTo: null},
        {name: 'Eevee', types: ['Normal'], evolCandy: '25 Eevee', eggKm: 10, evolFrom: null, evolTo: ['Vaporeon', 'Jolteon', 'Flareon']},
        {name: 'Ekans', types: ['Poison'], evolCandy: '50 Ekans', eggKm: 5, evolFrom: null, evolTo: ['Arbok']},
        {name: 'Electabuzz', types: ['Electric'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Electrode', types: ['Electric'], evolCandy: null, eggKm: null, evolFrom: ['Voltorb'], evolTo: null},
        {name: 'Exeggcute', types: ['Grass', 'Psychic'], evolCandy: '50 Exeggcute', eggKm: 5, evolFrom: null, evolTo: ['Exeggutor']},
        {name: 'Exeggutor', types: ['Grass', 'Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Exeggcute'], evolTo: null},
        {name: 'Farfetch\'d', types: ['Normal', 'Flying'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null},
        {name: 'Fearow', types: ['Normal', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Spearow'], evolTo: null},
        {name: 'Flareon', types: ['Fire'], evolCandy: null, eggKm: null, evolFrom: ['Eevee'], evolTo: null},
        {name: 'Gastly', types: ['Ghost', 'Poison'], evolCandy: '25 Gastly', eggKm: 5, evolFrom: null, evolTo: ['Haunter']},
        {name: 'Gengar', types: ['Ghost', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Haunter'], evolTo: null},
        {name: 'Geodude', types: ['Rock', 'Ground'], evolCandy: '25 Geodude', eggKm: 2, evolFrom: null, evolTo: ['Graveler']},
        {name: 'Gloom', types: ['Grass', 'Poison'], evolCandy: '100 Oddish', eggKm: null, evolFrom: ['Oddish'], evolTo: ['Vileplume']},
        {name: 'Golbat', types: ['Poison', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Zubat'], evolTo: null},
        {name: 'Goldeen', types: ['Water'], evolCandy: '50 Goldeen', eggKm: 5, evolFrom: null, evolTo: ['Seaking']},
        {name: 'Golduck', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Psyduck'], evolTo: null},
        {name: 'Golem', types: ['Rock', 'Ground'], evolCandy: null, eggKm: null, evolFrom: ['Graveler'], evolTo: null},
        {name: 'Graveler', types: ['Rock', 'Ground'], evolCandy: '100 Geodude', eggKm: null, evolFrom: ['Geodude'], evolTo: ['Golem']},
        {name: 'Grimer', types: ['Poison'], evolCandy: '50 Grimer', eggKm: 5, evolFrom: null, evolTo: ['Muk']},
        {name: 'Growlithe', types: ['Fire'], evolCandy: '50 Growlithe', eggKm: 5, evolFrom: null, evolTo: ['Arcanine']},
        {name: 'Gyarados', types: ['Water', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Magikarp'], evolTo: ['Gyarados']},
        {name: 'Haunter', types: ['Ghost', 'Poison'], evolCandy: '100 Gastly', eggKm: null, evolFrom: ['Gastly'], evolTo: ['Gengar']},
        {name: 'Hitmonchan', types: ['Fight'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Hitmonlee', types: ['Fight'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Horsea', types: ['Water'], evolCandy: '50 Horsea', eggKm: 5, evolFrom: null, evolTo: ['Seadra']},
        {name: 'Hypno', types: ['Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Drowzee'], evolTo: null},
        {name: 'Ivysaur', types: ['Grass', 'Poison'], evolCandy: '100 Bulbasaur', eggKm: null, evolFrom: ['Bulbasaur'], evolTo: ['Venusaur']},
        {name: 'Jigglypuff', types: ['Normal', 'Fairy'], evolCandy: '50 Jigglypuff', eggKm: 2, evolFrom: null, evolTo: ['Wigglytuff']},
        {name: 'Jolteon', types: ['Electric'], evolCandy: null, eggKm: null, evolFrom: ['Eevee'], evolTo: null},
        {name: 'Jynx', types: ['Ice', 'Psychic'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Kabuto', types: ['Rock', 'Water'], evolCandy: '50 Kabuto', eggKm: 10, evolFrom: null, evolTo: ['Kabutops']},
        {name: 'Kabutops', types: ['Rock', 'Water'], evolCandy: null, eggKm: null, evolFrom: ['Kabuto'], evolTo: null},
        {name: 'Kadabra', types: ['Psychic'], evolCandy: '100 Abra', eggKm: null, evolFrom: ['Abra'], evolTo: ['Alakazam']},
        {name: 'Kakuna', types: ['Bug', 'Poison'], evolCandy: '50 Weedle', eggKm: null, evolFrom: ['Weedle'], evolTo: ['Beedrill']},
        {name: 'Kangaskhan', types: ['Normal'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null},
        {name: 'Kingler', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Krabby'], evolTo: null},
        {name: 'Koffing', types: ['Poison'], evolCandy: '50 Koffing', eggKm: 5, evolFrom: null, evolTo: ['Weezing']},
        {name: 'Krabby', types: ['Water'], evolCandy: '50 Krabby', eggKm: 5, evolFrom: null, evolTo: ['Kingler']},
        {name: 'Lapras', types: ['Water', 'Ice'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Lickitung', types: ['Normal'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null},
        {name: 'Machamp', types: ['Fight'], evolCandy: null, eggKm: null, evolFrom: ['Machoke'], evolTo: null},
        {name: 'Machoke', types: ['Fight'], evolCandy: '100 Machop', eggKm: null, evolFrom: ['Machop'], evolTo: ['Machamp']},
        {name: 'Machop', types: ['Fight'], evolCandy: '25 Machop', eggKm: 5, evolFrom: null, evolTo: ['Machoke']},
        {name: 'Magikarp', types: ['Water'], evolCandy: '400 Magikarp', eggKm: 2, evolFrom: null, evolTo: ['Gyarados']},
        {name: 'Magmar', types: ['Fire'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Magnemite', types: ['Electric', 'Steel'], evolCandy: '50 Magnemite', eggKm: 5, evolFrom: null, evolTo: ['Magneton']},
        {name: 'Magneton', types: ['Electric', 'Steel'], evolCandy: null, eggKm: null, evolFrom: ['Magnemite'], evolTo: null},
        {name: 'Mankey', types: ['Fight'], evolCandy: '50 Mankey', eggKm: 5, evolFrom: null, evolTo: ['Primeape']},
        {name: 'Marowak', types: ['Ground'], evolCandy: null, eggKm: null, evolFrom: ['Cubone'], evolTo: null},
        {name: 'Meowth', types: ['Normal'], evolCandy: '50 Meowth', eggKm: 5, evolFrom: null, evolTo: ['Persian']},
        {name: 'Metapod', types: ['Bug'], evolCandy: '50 Caterpie', eggKm: null, evolFrom: ['Caterpie'], evolTo: ['Butterfree']},
        {name: 'Mew', types: ['Psychic'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null},
        {name: 'Mewtwo', types: ['Psychic'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null},
        {name: 'Moltres', types: ['Fire', 'Flying'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null},
        {name: 'Mr. Mime', types: ['Psychic', 'Fairy'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Muk', types: ['Poison'], evolCandy: null, eggKm: null, evolFrom: ['Grimer'], evolTo: null},
        {name: 'Nidoking', types: ['Poison', 'Ground'], evolCandy: null, eggKm: null, evolFrom: ['Nidorino'], evolTo: null},
        {name: 'Nidoqueen', types: ['Poison', 'Ground'], evolCandy: null, eggKm: null, evolFrom: ['Nidorina'], evolTo: null},
        {name: 'Nidoran♀', types: ['Poison'], evolCandy: '25 Nidoran♀', eggKm: 5, evolFrom: [''], evolTo: ['Nidorina']},
        {name: 'Nidoran♂', types: ['Poison'], evolCandy: '25 Nidoran♂', eggKm: 5, evolFrom: null, evolTo: ['Nidorino']},
        {name: 'Nidorina', types: ['Poison'], evolCandy: '100 Nidoran♀', eggKm: null, evolFrom: ['Nidoran♀'], evolTo: ['Nidoqueen']},
        {name: 'Nidorino', types: ['Poison'], evolCandy: '100 Nidoran♂', eggKm: null, evolFrom: ['Nidoran♂'], evolTo: ['Nidoking']},
        {name: 'Ninetales', types: ['Fire'], evolCandy: null, eggKm: null, evolFrom: ['Vulpix'], evolTo: null},
        {name: 'Oddish', types: ['Grass', 'Poison'], evolCandy: '25 Oddish', eggKm: 5, evolFrom: null, evolTo: ['Gloom']},
        {name: 'Omanyte', types: ['Rock', 'Water'], evolCandy: '50 Omanyte', eggKm: 10, evolFrom: null, evolTo: ['Omastar']},
        {name: 'Omastar', types: ['Rock', 'Water'], evolCandy: null, eggKm: null, evolFrom: ['Omanyte'], evolTo: null},
        {name: 'Onix', types: ['Rock', 'Ground'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Paras', types: ['Bug', 'Grass'], evolCandy: '50 Paras', eggKm: 5, evolFrom: null, evolTo: ['Parasect']},
        {name: 'Parasect', types: ['Bug', 'Grass'], evolCandy: null, eggKm: null, evolFrom: ['Paras'], evolTo: null},
        {name: 'Persian', types: ['Normal'], evolCandy: null, eggKm: null, evolFrom: ['Meowth'], evolTo: null},
        {name: 'Pidgeot', types: ['Normal', 'Flying'], evolCandy: null, eggKm: null, evolFrom: ['Pidgeotto'], evolTo: null},
        {name: 'Pidgeotto', types: ['Normal', 'Flying'], evolCandy: '50 Pidgey', eggKm: null, evolFrom: ['Pidgey'], evolTo: ['Pidgeot']},
        {name: 'Pidgey', types: ['Normal', 'Flying'], evolCandy: '12 Pidgey', eggKm: 2, evolFrom: null, evolTo: ['Pidgeotto']},
        {name: 'Pikachu', types: ['Electric'], evolCandy: '50 Pikachu', eggKm: 2, evolFrom: null, evolTo: ['Raichu']},
        {name: 'Pinsir', types: ['Bug'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Poliwag', types: ['Water'], evolCandy: '25 Poliwag', eggKm: 5, evolFrom: null, evolTo: ['Poliwhirl']},
        {name: 'Poliwhirl', types: ['Water'], evolCandy: '100 Poliwag', eggKm: null, evolFrom: ['Poliwag'], evolTo: ['Poliwrath']},
        {name: 'Poliwrath', types: ['Water', 'Fight'], evolCandy: null, eggKm: null, evolFrom: ['Poliwhirl'], evolTo: null},
        {name: 'Ponyta', types: ['Fire'], evolCandy: '50 Ponyta', eggKm: 5, evolFrom: null, evolTo: ['Rapidash']},
        {name: 'Porygon', types: ['Normal'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null},
        {name: 'Primeape', types: ['Fight'], evolCandy: null, eggKm: null, evolFrom: ['Mankey'], evolTo: null},
        {name: 'Psyduck', types: ['Water'], evolCandy: '50 Psyduck', eggKm: 5, evolFrom: null, evolTo: ['Golduck']},
        {name: 'Raichu', types: ['Electric'], evolCandy: null, eggKm: null, evolFrom: ['Pikachu'], evolTo: null},
        {name: 'Rapidash', types: ['Fire'], evolCandy: null, eggKm: null, evolFrom: ['Ponyta'], evolTo: null},
        {name: 'Raticate', types: ['Normal'], evolCandy: null, eggKm: null, evolFrom: ['Rattata'], evolTo: null},
        {name: 'Rattata', types: ['Normal'], evolCandy: '25 Rattata', eggKm: 2, evolFrom: null, evolTo: ['Raticate']},
        {name: 'Rhydon', types: ['Ground', 'Rock'], evolCandy: null, eggKm: null, evolFrom: ['Rhyhorn'], evolTo: null},
        {name: 'Rhyhorn', types: ['Ground', 'Rock'], evolCandy: '50 Rhyhorn', eggKm: 5, evolFrom: null, evolTo: ['Rhydon']},
        {name: 'Sandshrew', types: ['Ground'], evolCandy: '50 Sandshrew', eggKm: 5, evolFrom: null, evolTo: ['Sandslash']},
        {name: 'Sandslash', types: ['Ground'], evolCandy: null, eggKm: null, evolFrom: ['Sandshrew'], evolTo: null},
        {name: 'Scyther', types: ['Bug', 'Flying'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Seadra', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Horsea'], evolTo: null},
        {name: 'Seaking', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Goldeen'], evolTo: [null]},
        {name: 'Seel', types: ['Water'], evolCandy: '50 Seel', eggKm: 5, evolFrom: null, evolTo: ['Dewgong']},
        {name: 'Shellder', types: ['Water'], evolCandy: '50 Shellder', eggKm: 5, evolFrom: null, evolTo: ['Cloyster']},
        {name: 'Slowbro', types: ['Water', 'Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Slowpoke'], evolTo: null},
        {name: 'Slowpoke', types: ['Water', 'Psychic'], evolCandy: '50 Slowpoke', eggKm: 5, evolFrom: null, evolTo: ['Slowbro']},
        {name: 'Snorlax', types: ['Normal'], evolCandy: null, eggKm: 10, evolFrom: null, evolTo: null},
        {name: 'Spearow', types: ['Normal', 'Flying'], evolCandy: '50 Spearow', eggKm: 2, evolFrom: null, evolTo: ['Fearow']},
        {name: 'Squirtle', types: ['Water'], evolCandy: '25 Squirtle', eggKm: 2, evolFrom: null, evolTo: ['Wartortle']},
        {name: 'Starmie', types: ['Water', 'Psychic'], evolCandy: null, eggKm: null, evolFrom: ['Staryu'], evolTo: null},
        {name: 'Staryu', types: ['Water'], evolCandy: '50 Staryu', eggKm: 5, evolFrom: null, evolTo: ['Starmie']},
        {name: 'Tangela', types: ['Grass'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null},
        {name: 'Tauros', types: ['Normal'], evolCandy: null, eggKm: 5, evolFrom: null, evolTo: null},
        {name: 'Tentacool', types: ['Water', 'Poison'], evolCandy: '50 Tentacool', eggKm: 5, evolFrom: null, evolTo: ['Tentacruel']},
        {name: 'Tentacruel', types: ['Water', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Tentacool'], evolTo: null},
        {name: 'Vaporeon', types: ['Water'], evolCandy: null, eggKm: null, evolFrom: ['Eevee'], evolTo: null},
        {name: 'Venomoth', types: ['Bug', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Venonat'], evolTo: null},
        {name: 'Venonat', types: ['Bug', 'Poison'], evolCandy: '50 Venonat', eggKm: 5, evolFrom: null, evolTo: ['Venomoth']},
        {name: 'Venusaur', types: ['Grass', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Ivysaur'], evolTo: null},
        {name: 'Victreebel', types: ['Grass', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Weepinbell'], evolTo: null},
        {name: 'Vileplume', types: ['Grass', 'Poison'], evolCandy: null, eggKm: null, evolFrom: ['Gloom'], evolTo: null},
        {name: 'Voltorb', types: ['Electric'], evolCandy: '50 Voltorb', eggKm: 5, evolFrom: null, evolTo: ['Electrode']},
        {name: 'Vulpix', types: ['Fire'], evolCandy: '50 Vulpix', eggKm: 5, evolFrom: null, evolTo: ['Ninetales']},
        {name: 'Wartortle', types: ['Water'], evolCandy: '100 Squirtle', eggKm: null, evolFrom: ['Squirtle'], evolTo: ['Blastoise']},
        {name: 'Weedle', types: ['Bug', 'Poison'], evolCandy: '12 Weedle', eggKm: 2, evolFrom: null, evolTo: ['Kakuna']},
        {name: 'Weepinbell', types: ['Grass', 'Poison'], evolCandy: '100 Bellsprout', eggKm: null, evolFrom: ['Bellsprout'], evolTo: ['Victreebel']},
        {name: 'Weezing', types: ['Poison'], evolCandy: null, eggKm: null, evolFrom: ['Koffing'], evolTo: null},
        {name: 'Wigglytuff', types: ['Normal', 'Fairy'], evolCandy: null, eggKm: null, evolFrom: ['Jigglypuff'], evolTo: null},
        {name: 'Zapdos', types: ['Electric', 'Flying'], evolCandy: null, eggKm: null, evolFrom: null, evolTo: null},
        {name: 'Zubat', types: ['Poison', 'Flying'], evolCandy: '50 Zubat', eggKm: 2, evolFrom: null, evolTo: ['Golbat']}
    ];

  }

  itemTapped(event, pokemon) {
    this.nav.push(ItemDetailsPage, {
      pokemon: pokemon
    });
  }
}
